### ISSUE TITLE
Refactor da arvore de fontes de dados para um SELECT MULTIPLE COM OPTION GROUP CSS ###URGENTE!

### ISSUE THREAD

**Issue by morettic2015** [morettic2015/smartcities#17]
![bug07](https://cloud.githubusercontent.com/assets/11476006/8426663/fd0b155e-1ee7-11e5-90b0-99d46c7d4497.png)

Nas fontes de dados nao iremos mais utilizar a arvore para apresentar os dados.

No lugar da arvore iremos utilizar um componente simples 

![image](https://cloud.githubusercontent.com/assets/11476006/8426688/2adcdddc-1ee8-11e5-923c-6360efb3f28b.png)

**Comment by morettic2015** [comment]
Da uma olhada no codigo HTML da imagem no exemplo. É para subsistuir a arvore por aquele componente HTML com todas as categorias de dados que temos no sistema como um agrupador.

**Comment by mauriciogomes** [comment]
A tree foi substituida por uma elemento select com optgroup

**Comment by mauriciogomes** [comment]
Agora tem duas funções que servirão para preencher a lista de data Sources e a de pendências.
