### ISSUE TITLE
Bug Validação email (underline nao aceita!)

### ISSUE THREAD

**Issue by morettic2015** [morettic2015/smartcities#19]
![image](https://cloud.githubusercontent.com/assets/11476006/8427517/65904ec2-1eee-11e5-904a-c22a550f8ffe.png)

Se tiver um underline como fica/????

**Comment by morettic2015** [comment]
Expressão regular para email....

^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)_@"    + "[A-Za-z0-9-]+(\.[A-Za-z0-9]+)_(\.[A-Za-z]{2,})$

**Comment by mauriciogomes** [comment]
Essa expressão regular não funcionou. Mas eu tenho uma dúvida: será que existe nome de usuário de email que começa ou termina com underline?

**Comment by mauriciogomes** [comment]
Descobri que contas da Microsoft permitem que o apelido termine com underline. Ajuste feito.
