### ISSUE TITLE
Informações sobre Download e Execução do Sistema

### ISSUE THREAD

**Issue by tacianosilva** [morettic2015/smartcities#2]
Olá @mauriciogomes,

Sou pesquisador e na minha busca por sistemas encontrei o smartcities. Se possível, gostaria de fazer algumas perguntas:

1- Gostaria de saber como é feita a persistência de dados (não encontrei no repositório)? Está usando JPA?

2- Quais os requisitos para executar o sistema?

3- Há alguma descrição das funcionalidades e das ferramentas utilizadas pelo smartcities?

Desde já agradeço!

**Comment by mauriciogomes** [comment]
Olá Taciano,

Segundo o idealizador do projeto, esse repositório não será mais de domínio
público. No momento é a informação que posso fornecer.

Att.
Mauricio

Em 11 de junho de 2015 10:40, Taciano Morais Silva <notifications@github.com

> escreveu:
> 
> Olá @mauriciogomes https://github.com/mauriciogomes,
> 
> Sou pesquisador e na minha busca por sistemas encontrei o smartcities. Se
> possível, gostaria de fazer algumas perguntas:
> 
> 1- Gostaria de saber como é feita a persistência de dados (não encontrei
> no repositório)? Está usando JPA?
> 
> 2- Quais os requisitos para executar o sistema?
> 
> 3- Há alguma descrição das funcionalidades e das ferramentas utilizadas
> pelo smartcities?
> 
> Desde já agradeço!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/morettic2015/smartcities/issues/2.

## 

Att.
Maurício Jacques Gomes

**Comment by tacianosilva** [comment]
Ok, ficarei acompanhando o projeto mesmo assim!

Att,
Taciano

**Comment by morettic2015** [comment]
Prezado Taciano,

Este é um projeto financiado pelo Governo do estado de SC através do edital Sinapse. Se tiveres interesse em conhecer o projeto e quem sabe utilizar dentro de um escopo acadêmico podemos conversar a respeito. Meu contato é malacma@gmail.com ou luisaugustomachadomoretto via SKP.

Certo de sua compreensão

**Comment by tacianosilva** [comment]
Obrigado pela atenção!

Mandarei o e-mail para conversarmos a respeito!

Abraços!
