### ISSUE TITLE
Dados do usuário não estão carregando

### ISSUE THREAD

**Issue by mauriciogomes** [morettic2015/smartcities#29]
Nos testes que fiz no Chrome, ao logar e carregar os dados do usuário, está ocorrendo um NullPointerException no getUserContext (chamado pelo /ctx) de ProfileEndpoint.
Pode ser que o id esteja nulo. Esse problema está dificultando a realização de outros testes.

**Comment by morettic2015** [comment]
problema no mapeamento do hibernate. Nao permitia coluna not null levando valores null.
