### ISSUE TITLE
LOJA ALTERAR LAYOUT

### ISSUE THREAD

**Issue by morettic2015** [morettic2015/smartcities#31]
TROCAR O ICONE PARA O SEGUNDO DA LISTA conforme o item #15 
#15

A LOJA ESTA DIFERENTE. Deve o estilo do link acima coloca o icone acima como o default. Faz igual ao design.

**Comment by morettic2015** [comment]
Na loja deve ter um ícone comprar e outro ícone importar tipo uma seta pra baixo como download.  Esses icones ficam dentro da caixa do serviço. Fica um retangulo com o icone default fundo cinza, texto descricao nome e os icones acima. Se precisar solicita para o guime os icones.

**Comment by mauriciogomes** [comment]
Quase terminado, só faltam os ícones que vou pedir ao João.

**Comment by mauriciogomes** [comment]
Concluí o layout. Talvez precise de alguma melhoria depois.

**Comment by mauriciogomes** [comment]
No momento o layout está bastante consistente.
