### ISSUE TITLE
Mascara de telefone

### ISSUE THREAD

**Issue by morettic2015** [morettic2015/smartcities#5]
As mascaras de telefone devem ser no formato +554896004929

**Comment by mauriciogomes** [comment]
Ajuste feito. Eu coloquei espaço entre o código de país, área e número, porque achei que melhora a experiencia do usuário, para não se perder nos números "colados". Se precisar mudar é só falar.
Atualizar app.js para testar.

**Comment by morettic2015** [comment]
Fechou
